version: '3.1'
services:
  web:
    image: cms/php73-apache
    build: ./cms-php73-apache
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres